//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetahookInstallerAvalonia.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetahookInstallerAvalonia.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Available Plugins: 的本地化字符串。
        /// </summary>
        public static string AvailablePlugins {
            get {
                return ResourceManager.GetString("AvailablePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Build folder cannot be located. Please extract all files to a folder before running the programme. 的本地化字符串。
        /// </summary>
        public static string BuildDirectoryNotFound {
            get {
                return ResourceManager.GetString("BuildDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelled 的本地化字符串。
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing the new file will replace the original file, and this operation cannot be reversed. 的本地化字符串。
        /// </summary>
        public static string ConfirmInstall {
            get {
                return ResourceManager.GetString("ConfirmInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmed to apply modification? 的本地化字符串。
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstalling will remove all Metahook-related files, including the metahook folder, and this action cannot be reversed. 的本地化字符串。
        /// </summary>
        public static string ConfirmUninstall {
            get {
                return ResourceManager.GetString("ConfirmUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Error 的本地化字符串。
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Game 的本地化字符串。
        /// </summary>
        public static string CustomGame {
            get {
                return ResourceManager.GetString("CustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed when deleting {0}. Error message {1}. 的本地化字符串。
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled Plugins: 的本地化字符串。
        /// </summary>
        public static string EnabledPlugins {
            get {
                return ResourceManager.GetString("EnabledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not found {0}. 的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source files 的本地化字符串。
        /// </summary>
        public static string Folder_Build {
            get {
                return ResourceManager.GetString("Folder_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metahook Config 的本地化字符串。
        /// </summary>
        public static string Folder_Config {
            get {
                return ResourceManager.GetString("Folder_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 的本地化字符串。
        /// </summary>
        public static string Folder_Game {
            get {
                return ResourceManager.GetString("Folder_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Contents 的本地化字符串。
        /// </summary>
        public static string Folder_GameContent {
            get {
                return ResourceManager.GetString("Folder_GameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed 的本地化字符串。
        /// </summary>
        public static string Folder_Installed {
            get {
                return ResourceManager.GetString("Folder_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metahook 的本地化字符串。
        /// </summary>
        public static string Folder_Mod {
            get {
                return ResourceManager.GetString("Folder_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metahook Contents 的本地化字符串。
        /// </summary>
        public static string Folder_ModContent {
            get {
                return ResourceManager.GetString("Folder_ModContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Models 的本地化字符串。
        /// </summary>
        public static string Folder_Models {
            get {
                return ResourceManager.GetString("Folder_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player Models 的本地化字符串。
        /// </summary>
        public static string Folder_Player {
            get {
                return ResourceManager.GetString("Folder_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scripts 的本地化字符串。
        /// </summary>
        public static string Folder_Scripts {
            get {
                return ResourceManager.GetString("Folder_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sound 的本地化字符串。
        /// </summary>
        public static string Folder_Sound {
            get {
                return ResourceManager.GetString("Folder_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprites 的本地化字符串。
        /// </summary>
        public static string Folder_Sprites {
            get {
                return ResourceManager.GetString("Folder_Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Path: 的本地化字符串。
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Mod finished! 的本地化字符串。
        /// </summary>
        public static string InstallDone {
            get {
                return ResourceManager.GetString("InstallDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid instal target. 的本地化字符串。
        /// </summary>
        public static string InvalidInstallPath {
            get {
                return ResourceManager.GetString("InvalidInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Lang_CN {
            get {
                return ResourceManager.GetString("Lang_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Lang_US {
            get {
                return ResourceManager.GetString("Lang_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MetaHook Installer 的本地化字符串。
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Path: 的本地化字符串。
        /// </summary>
        public static string ModPath {
            get {
                return ResourceManager.GetString("ModPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open.. 的本地化字符串。
        /// </summary>
        public static string OpenView {
            get {
                return ResourceManager.GetString("OpenView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset finished 的本地化字符串。
        /// </summary>
        public static string ResetDone {
            get {
                return ResourceManager.GetString("ResetDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved. 的本地化字符串。
        /// </summary>
        public static string SaveDone {
            get {
                return ResourceManager.GetString("SaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please install mod first. 的本地化字符串。
        /// </summary>
        public static string SelectFirst {
            get {
                return ResourceManager.GetString("SelectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Game: 的本地化字符串。
        /// </summary>
        public static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam AppId: 的本地化字符串。
        /// </summary>
        public static string SteamAppId {
            get {
                return ResourceManager.GetString("SteamAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success! 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor 的本地化字符串。
        /// </summary>
        public static string Tab_Edit {
            get {
                return ResourceManager.GetString("Tab_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Tab_Install {
            get {
                return ResourceManager.GetString("Tab_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Tab_Open {
            get {
                return ResourceManager.GetString("Tab_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall finished. 的本地化字符串。
        /// </summary>
        public static string UninstallDone {
            get {
                return ResourceManager.GetString("UninstallDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation failed due to an error. 的本地化字符串。
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstallation failed due to an error. 的本地化字符串。
        /// </summary>
        public static string UninstallationFailed {
            get {
                return ResourceManager.GetString("UninstallationFailed", resourceCulture);
            }
        }
    }
}
