using BSPLocalizationTools.GUI.Lang;

namespace BSPLocalizationTools.GUI.ViewModels;

public sealed record LocalizedStrings(
    string AppTitle,
    string TranslateTab,
    string SettingsTab,
    string TargetLanguage,
    string AddBsp,
    string Clear,
    string Start,
    string Cancel,
    string ConfigurationFile,
    string Load,
    string Save,
    string PromptFile,
    string PromptFileWatermark,
    string Browse,
    string Llm,
    string Model,
    string ApiKey,
    string BaseUrl,
    string Temperature,
    string ReasoningEffort,
    string FakeAs,
    string Defaults,
    string GuiLanguage,
    string SelectBspFilesTitle,
    string GoldSrcBspFilter,
    string SelectPromptFileTitle,
    string MarkdownFilter)
{
    public static LocalizedStrings Current() => new(
        Resources.AppTitle,
        Resources.TranslateTab,
        Resources.SettingsTab,
        Resources.TargetLanguage,
        Resources.AddBsp,
        Resources.Clear,
        Resources.Start,
        Resources.Cancel,
        Resources.ConfigurationFile,
        Resources.Load,
        Resources.Save,
        Resources.PromptFile,
        Resources.PromptFileWatermark,
        Resources.Browse,
        Resources.Llm,
        Resources.Model,
        Resources.ApiKey,
        Resources.BaseUrl,
        Resources.Temperature,
        Resources.ReasoningEffort,
        Resources.FakeAs,
        Resources.Defaults,
        Resources.GuiLanguage,
        Resources.SelectBspFilesTitle,
        Resources.GoldSrcBspFilter,
        Resources.SelectPromptFileTitle,
        Resources.MarkdownFilter);
}
