using BSPLocalizationTools.GUI.Lang;

namespace BSPLocalizationTools.GUI.ViewModels;

public sealed record LocalizedStrings(
    string AppTitle,
    string TranslateTab,
    string SettingsTab,
    string TargetLanguage,
    string AddBsp,
    string Clear,
    string ClearCompletedTasks,
    string RemoveTask,
    string ViewRawGameText,
    string RawGameTextTitle,
    string NoGameTextFound,
    string FailedToLoadGameText,
    string Start,
    string Cancel,
    string ConfigurationFile,
    string Load,
    string Save,
    string SaveConfigurationSucceededTitle,
    string SaveConfigurationSucceededMessage,
    string Ok,
    string PromptFile,
    string PromptFileWatermark,
    string Browse,
    string PromptEditor,
    string PromptEditorWatermark,
    string LoadBuiltInPrompt,
    string ReloadPromptFromFile,
    string SavePromptFile,
    string SavePromptFileTitle,
    string Llm,
    string Model,
    string ApiKey,
    string BaseUrl,
    string Temperature,
    string ReasoningEffort,
    string FakeAs,
    string Defaults,
    string AppendLanguageToCsvFileName,
    string GuiLanguage,
    string SelectBspFilesTitle,
    string GoldSrcBspFilter,
    string SelectPromptFileTitle,
    string MarkdownFilter)
{
    public static LocalizedStrings Current() => new(
        Resources.AppTitle,
        Resources.TranslateTab,
        Resources.SettingsTab,
        Resources.TargetLanguage,
        Resources.AddBsp,
        Resources.Clear,
        Resources.ClearCompletedTasks,
        Resources.RemoveTask,
        Resources.ViewRawGameText,
        Resources.RawGameTextTitle,
        Resources.NoGameTextFound,
        Resources.FailedToLoadGameText,
        Resources.Start,
        Resources.Cancel,
        Resources.ConfigurationFile,
        Resources.Load,
        Resources.Save,
        Resources.SaveConfigurationSucceededTitle,
        Resources.SaveConfigurationSucceededMessage,
        Resources.Ok,
        Resources.PromptFile,
        Resources.PromptFileWatermark,
        Resources.Browse,
        Resources.PromptEditor,
        Resources.PromptEditorWatermark,
        Resources.LoadBuiltInPrompt,
        Resources.ReloadPromptFromFile,
        Resources.SavePromptFile,
        Resources.SavePromptFileTitle,
        Resources.Llm,
        Resources.Model,
        Resources.ApiKey,
        Resources.BaseUrl,
        Resources.Temperature,
        Resources.ReasoningEffort,
        Resources.FakeAs,
        Resources.Defaults,
        Resources.AppendLanguageToCsvFileName,
        Resources.GuiLanguage,
        Resources.SelectBspFilesTitle,
        Resources.GoldSrcBspFilter,
        Resources.SelectPromptFileTitle,
        Resources.MarkdownFilter);
}
