# Component registry: <path>|<group>|<per-component option>|<injected dep vars>|<default, optional>
# Dependency vars are comma-separated; '-' means the component fetches everything
# itself. (';' cannot be used: it is a CMake list separator even inside quotes.)
# The optional fifth field is the option default: use 0 for components that
# should stay out of the aggregate unless explicitly re-enabled with -D<opt>=ON.
# Order matters only for shared vendor targets: the first component that adds
# libglew_static / FreeImage owns them, later ones reuse them.
set(METAHOOKSV_COMPONENT_DEFS
    "MetaHook|metahook|METAHOOKSV_BUILD_METAHOOK|FORMAT_VALIDATION_SOURCE_PATH"
    "PluginLibs/SteamAPIBridge|pluginlibs|METAHOOKSV_BUILD_PLUGINLIB_STEAMAPIBRIDGE|STEAMSDK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"

    "Plugins/BulletPhysics|plugins|METAHOOKSV_BUILD_PLUGIN_BULLETPHYSICS|METAHOOK_SOURCE_PATH,VGUI2EXTENSION_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,GLEW_SOURCE_PATH,TINYOBJLOADER_SOURCE_PATH,CHOCOBO1HASH_SOURCE_PATH,BULLET3_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/CaptionMod|plugins|METAHOOKSV_BUILD_PLUGIN_CAPTIONMOD|METAHOOK_SOURCE_PATH,VGUI2EXTENSION_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/HeapPatch|plugins|METAHOOKSV_BUILD_PLUGIN_HEAPPATCH|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/InterpFix|plugins|METAHOOKSV_BUILD_PLUGIN_INTERPFIX|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/PrecacheManager|plugins|METAHOOKSV_BUILD_PLUGIN_PRECACHEMANAGER|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/Renderer|plugins|METAHOOKSV_BUILD_PLUGIN_RENDERER|METAHOOK_SOURCE_PATH,VGUI2EXTENSION_SOURCE_PATH,UTILTHREADTASK_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,GLEW_SOURCE_PATH,FREEIMAGE_SOURCE_PATH,TINYOBJLOADER_SOURCE_PATH,SDL2_INCLUDE_DIRS,SDL3_INCLUDE_DIRS,GLFW_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/BetterSpray|plugins|METAHOOKSV_BUILD_PLUGIN_BETTERSPRAY|METAHOOK_SOURCE_PATH,VGUI2EXTENSION_SOURCE_PATH,UTILTHREADTASK_SOURCE_PATH,UTILHTTPCLIENT_SOURCE_PATH,STEAMSDK_SOURCE_PATH,STEAMAPIBRIDGE_SOURCE_PATH,FREEIMAGE_SOURCE_PATH,LIBXML2_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,CHOCOBO1HASH_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/ResourceReplacer|plugins|METAHOOKSV_BUILD_PLUGIN_RESOURCEREPLACER|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/SCCameraFix|plugins|METAHOOKSV_BUILD_PLUGIN_SCCAMERAFIX|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/SCModelDownloader|plugins|METAHOOKSV_BUILD_PLUGIN_SCMODELDOWNLOADER|METAHOOK_SOURCE_PATH,VGUI2EXTENSION_SOURCE_PATH,UTILASSETSINTEGRITY_SOURCE_PATH,UTILHTTPCLIENT_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,RAPIDJSON_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/SteamScreenshots|plugins|METAHOOKSV_BUILD_PLUGIN_STEAMSCREENSHOTS|METAHOOK_SOURCE_PATH,STEAMSDK_SOURCE_PATH,STEAMAPIBRIDGE_SOURCE_PATH,GLEW_SOURCE_PATH,GLFW_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/StudioEvents|plugins|METAHOOKSV_BUILD_PLUGIN_STUDIOEVENTS|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/ThreadGuard|plugins|METAHOOKSV_BUILD_PLUGIN_THREADGUARD|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "Plugins/VGUI2Extension|plugins|METAHOOKSV_BUILD_PLUGIN_VGUI2EXTENSION|METAHOOK_SOURCE_PATH,SDL2_INCLUDE_DIRS,SDL3_INCLUDE_DIRS,FORMAT_VALIDATION_SOURCE_PATH"

    "PluginLibs/UtilAssetsIntegrity|pluginlibs|METAHOOKSV_BUILD_PLUGINLIB_UTILASSETSINTEGRITY|METAHOOK_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,FREEIMAGE_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "PluginLibs/UtilHTTPClient_SteamAPI|pluginlibs|METAHOOKSV_BUILD_PLUGINLIB_UTILHTTPCLIENT_STEAMAPI|METAHOOK_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,STEAMSDK_SOURCE_PATH,STEAMAPIBRIDGE_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "PluginLibs/UtilHTTPClient_libcurl|pluginlibs|METAHOOKSV_BUILD_PLUGINLIB_UTILHTTPCLIENT_LIBCURL|METAHOOK_SOURCE_PATH,SCOPEEXIT_SOURCE_PATH,CURL_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"
    "PluginLibs/UtilThreadTask|pluginlibs|METAHOOKSV_BUILD_PLUGINLIB_UTILTHREADTASK|METAHOOK_SOURCE_PATH,FORMAT_VALIDATION_SOURCE_PATH"

    # Standalone dev tool, currently unused by the aggregate; off by default so
    # its EXE/PDB stay out of the shared install. Re-enable with
    # -DMETAHOOKSV_BUILD_TOOL_STEAMAPPSLOCATION=ON.
    "toolsrc/SteamAppsLocation|toolsrc|METAHOOKSV_BUILD_TOOL_STEAMAPPSLOCATION|-|0"
)
