cmake_minimum_required(VERSION 3.21)
include("${SETTINGS}")
if(NOT CONFIG MATCHES "^(Debug|Release)$")
    message(FATAL_ERROR "LaunchGame requires Debug or Release.")
endif()

function(run_checked)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "LaunchGame command failed (${result}): ${ARGV0}")
    endif()
endfunction()

set(stage "${launch_root}/${CONFIG}")
file(MAKE_DIRECTORY "${stage}")
# Serialize deployments from this build tree, including Debug/Release switches.
file(LOCK "${launch_root}/deploy.lock" GUARD PROCESS TIMEOUT 120)
run_checked("${dotnet}" build "${cli_project}" --configuration "${CONFIG}" --output "${stage}" --nologo)
set(cli "${stage}/MetahookInstallerCLI.dll")
set(target_args -appid "${game_appid}" -gamedir "${game_directory}" -moddir "${game_mod}")
execute_process(COMMAND "${dotnet}" "${cli}" ${target_args} -describe-target
    WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result OUTPUT_VARIABLE description ERROR_VARIABLE error)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Cannot query the game before deployment: ${error}")
endif()
string(JSON current_launcher GET "${description}" LauncherPath)
if(NOT current_launcher STREQUAL launcher)
    message(FATAL_ERROR "The game's launcher changed. Reconfigure CMake before debugging. Expected '${launcher}', now '${current_launcher}'.")
endif()

# Only remove the private staging payload; never clean the game's directory.
# Resolve the paths before the recursive removal, including junctions/symlinks.
file(REAL_PATH "${binary_dir}" binary_real)
file(REAL_PATH "${stage}/install/output" payload_real)
file(REAL_PATH "${game_directory}" game_real)
set(expected_payload "${binary_real}/launch-game/${CONFIG}/install/output")
cmake_path(IS_PREFIX payload_real "${game_real}" NORMALIZE game_inside_payload)
cmake_path(IS_PREFIX game_real "${payload_real}" NORMALIZE payload_inside_game)
if(NOT payload_real STREQUAL expected_payload OR game_inside_payload OR payload_inside_game)
    message(FATAL_ERROR "Refusing to clean an unexpected or overlapping LaunchGame payload: ${payload_real}")
endif()
file(REMOVE_RECURSE "${payload_real}")
if(EXISTS "${payload_real}")
    message(FATAL_ERROR "Cannot clear the private LaunchGame payload (a file may be locked): ${payload_real}")
endif()
run_checked("${CMAKE_COMMAND}" --install "${binary_dir}" --config "${CONFIG}" --prefix "${payload_real}")
run_checked("${dotnet}" "${cli}" ${target_args} -include-debug-symbols)
message(STATUS "LaunchGame deployment ready: ${launcher}")
