cmake_minimum_required(VERSION 3.21)
include("${SETTINGS}")
if(NOT CONFIG MATCHES "^(Debug|Release)$")
    message(FATAL_ERROR "LaunchGame requires Debug or Release.")
endif()

function(run_checked)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "LaunchGame command failed (${result}): ${ARGV0}")
    endif()
endfunction()

set(stage "${launch_root}/${CONFIG}")
file(MAKE_DIRECTORY "${stage}")
# Serialize deployments from this build tree, including Debug/Release switches.
file(LOCK "${launch_root}/deploy.lock" GUARD PROCESS TIMEOUT 120)
if(cli_project)
    run_checked("${dotnet}" build "${cli_project}" --configuration "${CONFIG}" --output "${stage}" --nologo)
    set(cli_command "${dotnet}" "${stage}/MetahookInstallerCLI.dll")
else()
    run_checked("${CMAKE_COMMAND}" -E copy_if_different "${cli_executable}" "${stage}/MetahookInstallerCLI.exe")
    set(cli_command "${stage}/MetahookInstallerCLI.exe")
endif()
set(target_args -appid "${game_appid}" -gamedir "${game_directory}" -moddir "${game_mod}")
if(plugins_only)
    list(APPEND target_args -plugins-only)
endif()
execute_process(COMMAND ${cli_command} ${target_args} -describe-target
    WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result OUTPUT_VARIABLE description ERROR_VARIABLE error)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Cannot query the game before deployment: ${error}")
endif()
string(JSON current_launcher GET "${description}" LauncherPath)
if(NOT current_launcher STREQUAL launcher)
    message(FATAL_ERROR "The game's launcher changed. Reconfigure CMake before debugging. Expected '${launcher}', now '${current_launcher}'.")
endif()

# The payload is the shared install directory install/<arch>/<config>; it is
# cleared and re-staged so every F5 deploys a fresh, complete tree. Never touch
# the game's own directory. Resolve the paths before the recursive removal,
# including junctions/symlinks, and refuse unless the target is exactly the
# expected install directory and does not overlap the game.
set(payload "${install_dir_base}/${CONFIG}")
# Materialize the install base so REAL_PATH has no missing path to warn about.
file(MAKE_DIRECTORY "${install_dir_base}")
if(EXISTS "${payload}")
    file(REAL_PATH "${payload}" payload_real)
else()
    file(REAL_PATH "${install_dir_base}" base_real)
    set(payload_real "${base_real}/${CONFIG}")
endif()
if(EXISTS "${game_directory}")
    file(REAL_PATH "${game_directory}" game_real)
else()
    set(game_real "${game_directory}")
endif()
if(NOT payload_real STREQUAL "${install_dir_base}/${CONFIG}")
    message(FATAL_ERROR "Refusing to clean an unexpected LaunchGame payload: ${payload_real}")
endif()
cmake_path(IS_PREFIX payload_real "${game_real}" NORMALIZE game_inside_payload)
cmake_path(IS_PREFIX game_real "${payload_real}" NORMALIZE payload_inside_game)
if(game_inside_payload OR payload_inside_game)
    message(FATAL_ERROR "Refusing to clean a LaunchGame payload that overlaps the game directory: ${payload_real}")
endif()
file(REMOVE_RECURSE "${payload_real}")
if(EXISTS "${payload_real}")
    message(FATAL_ERROR "Cannot clear the LaunchGame payload (a file may be locked): ${payload_real}")
endif()
run_checked("${CMAKE_COMMAND}" --install "${binary_dir}" --config "${CONFIG}" --prefix "${payload_real}")
run_checked(${cli_command} ${target_args} -include-debug-symbols)
message(STATUS "LaunchGame deployment ready: ${launcher}")
