# The aggregator supplies one read-only shared tooling checkout to every component.
if(NOT DEFINED FORMAT_VALIDATION_SOURCE_PATH)
    set(_format_validation_default "$ENV{FORMAT_VALIDATION_SOURCE_PATH}")
    if(NOT _format_validation_default)
        set(_format_validation_default "${CMAKE_CURRENT_LIST_DIR}/../thirdparty/FormatValidation")
    endif()
    set(FORMAT_VALIDATION_SOURCE_PATH "${_format_validation_default}" CACHE PATH
        "Shared FormatValidation source tree")
endif()
if(NOT FORMAT_VALIDATION_SOURCE_PATH)
    set(FORMAT_VALIDATION_SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../thirdparty/FormatValidation")
endif()
get_filename_component(FORMAT_VALIDATION_SOURCE_PATH "${FORMAT_VALIDATION_SOURCE_PATH}"
    ABSOLUTE BASE_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
foreach(_format_validation_file .clang-format clang-format-validate.py cmake/FormatValidation.cmake)
    if(NOT EXISTS "${FORMAT_VALIDATION_SOURCE_PATH}/${_format_validation_file}")
        message(FATAL_ERROR "FORMAT_VALIDATION_SOURCE_PATH is missing ${_format_validation_file}: ${FORMAT_VALIDATION_SOURCE_PATH}. Initialize thirdparty/FormatValidation.")
    endif()
endforeach()
include("${FORMAT_VALIDATION_SOURCE_PATH}/cmake/FormatValidation.cmake")
configure_file("${FORMAT_VALIDATION_SOURCE_PATH}/.clang-format" "${CMAKE_CURRENT_LIST_DIR}/../.clang-format" COPYONLY)
add_custom_target(format-check)
add_custom_target(format)
set_target_properties(format-check format PROPERTIES FOLDER "FormatValidation")
foreach(_format_validation_definition IN LISTS METAHOOKSV_COMPONENT_DEFS)
    string(REPLACE "|" ";" _format_validation_fields "${_format_validation_definition}")
    list(GET _format_validation_fields 0 _format_validation_path)
    list(GET _format_validation_fields 1 _format_validation_group)
    if(_format_validation_group STREQUAL "toolsrc")
        continue()
    endif()
    get_filename_component(_format_validation_name "${_format_validation_path}" NAME)
    format_validation_add_component("${_format_validation_name}" "${CMAKE_CURRENT_LIST_DIR}/../${_format_validation_path}")
    add_dependencies(format-check "${_format_validation_name}-format-check")
    add_dependencies(format "${_format_validation_name}-format")
endforeach()
