# Cache a self-contained CLI; source builds and explicit overrides bypass this file.
include_guard(GLOBAL)

function(metahooksv_download_installer launch_root release out_executable)
    if(NOT release MATCHES "^[A-Za-z0-9_.-]+$" OR release STREQUAL "." OR release STREQUAL "..")
        message(FATAL_ERROR "METAHOOKSV_INSTALLER_RELEASE must be latest or a release tag.")
    endif()
    set(cache "${launch_root}/installer/${release}")
    file(MAKE_DIRECTORY "${cache}")
    file(LOCK "${cache}/download.lock" GUARD FUNCTION TIMEOUT 180)
    set(executable "${cache}/MetahookInstallerCLI.exe")
    if(EXISTS "${cache}/ready.json")
        file(READ "${cache}/ready.json" metadata)
        string(JSON expected_hash ERROR_VARIABLE error GET "${metadata}" sha256)
        if(error OR NOT EXISTS "${executable}")
            message(FATAL_ERROR "Incomplete InstallerCLI cache; clear ${cache} and reconfigure.")
        endif()
        file(SHA256 "${executable}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Corrupt InstallerCLI cache; clear ${cache} and reconfigure.")
        endif()
        string(JSON tag GET "${metadata}" tag)
    else()
        if(release STREQUAL "latest")
            set(endpoint latest)
        else()
            set(endpoint "tags/${release}")
        endif()
        # Optional API authentication avoids shared-IP rate limits. Never cache the token.
        set(api_headers HTTPHEADER "Accept: application/vnd.github+json" HTTPHEADER "User-Agent: MetaHookSv-CMake")
        if(NOT "$ENV{GH_TOKEN}" STREQUAL "")
            list(APPEND api_headers HTTPHEADER "Authorization: Bearer $ENV{GH_TOKEN}")
        elseif(NOT "$ENV{GITHUB_TOKEN}" STREQUAL "")
            list(APPEND api_headers HTTPHEADER "Authorization: Bearer $ENV{GITHUB_TOKEN}")
        endif()
        file(DOWNLOAD "https://api.github.com/repos/MetaHookSv/MetahookInstaller/releases/${endpoint}"
            "${cache}/release.json" TLS_VERIFY ON TIMEOUT 120 STATUS status
            ${api_headers})
        list(GET status 0 result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cannot query Installer release ${release}: ${status}. For GitHub API rate limits, set GH_TOKEN/GITHUB_TOKEN in the environment. Use METAHOOKSV_INSTALLER_CLI_EXECUTABLE for an offline CLI.")
        endif()
        file(READ "${cache}/release.json" metadata)
        string(JSON tag GET "${metadata}" tag_name)
        string(JSON count LENGTH "${metadata}" assets)
        set(url "")
        set(hash_args)
        if(count GREATER 0)
            math(EXPR last "${count} - 1")
            foreach(index RANGE 0 ${last})
                string(JSON name GET "${metadata}" assets ${index} name)
                if(name STREQUAL "MetahookInstaller-windows-x64.7z")
                    string(JSON url GET "${metadata}" assets ${index} browser_download_url)
                    string(JSON digest ERROR_VARIABLE error GET "${metadata}" assets ${index} digest)
                    if(NOT error AND digest MATCHES "^sha256:([0-9a-fA-F]+)$")
                        set(hash_args EXPECTED_HASH "SHA256=${CMAKE_MATCH_1}")
                    endif()
                    break()
                endif()
            endforeach()
        endif()
        if(NOT url)
            message(FATAL_ERROR "Installer release ${tag} has no MetahookInstaller-windows-x64.7z asset.")
        endif()
        file(DOWNLOAD "${url}" "${cache}/package.7z" ${hash_args}
            TLS_VERIFY ON TIMEOUT 300 INACTIVITY_TIMEOUT 60 SHOW_PROGRESS STATUS status)
        list(GET status 0 result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cannot download Installer ${tag}: ${status}")
        endif()
        # A unique private directory means interrupted extraction is never a cache hit.
        string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
        set(extracted "${cache}/extract-${nonce}")
        file(ARCHIVE_EXTRACT INPUT "${cache}/package.7z" DESTINATION "${extracted}"
            PATTERNS "*MetahookInstallerCLI.exe")
        file(GLOB_RECURSE candidates "${extracted}/*MetahookInstallerCLI.exe")
        list(LENGTH candidates count)
        if(NOT count EQUAL 1)
            message(FATAL_ERROR "Installer ${tag} must contain exactly one MetahookInstallerCLI.exe.")
        endif()
        list(GET candidates 0 candidate)
        execute_process(COMMAND "${candidate}" -help RESULT_VARIABLE result
            OUTPUT_VARIABLE help ERROR_VARIABLE error TIMEOUT 30)
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Downloaded InstallerCLI cannot run: ${result}\n${error}")
        endif()
        file(COPY_FILE "${candidate}" "${executable}" ONLY_IF_DIFFERENT)
        file(SHA256 "${executable}" actual_hash)
        string(JSON ready SET "{}" tag "\"${tag}\"")
        string(JSON ready SET "${ready}" sha256 "\"${actual_hash}\"")
        file(WRITE "${cache}/ready.json.tmp" "${ready}\n")
        file(RENAME "${cache}/ready.json.tmp" "${cache}/ready.json")
    endif()
    message(STATUS "InstallerCLI release: ${tag} (${cache})")
    set(${out_executable} "${executable}" PARENT_SCOPE)
endfunction()
