//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSPLocalizationTools.GUI.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSPLocalizationTools.GUI.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add BSP 的本地化字符串。
        /// </summary>
        public static string AddBsp {
            get {
                return ResourceManager.GetString("AddBsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API key 的本地化字符串。
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BSPLocalizationTools 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base URL 的本地化字符串。
        /// </summary>
        public static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear all tasks 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Clear completed tasks 的本地化字符串。
        /// </summary>
        public static string ClearCompletedTasks {
            get {
                return ResourceManager.GetString("ClearCompletedTasks", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Configuration file 的本地化字符串。
        /// </summary>
        public static string ConfigurationFile {
            get {
                return ResourceManager.GetString("ConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defaults 的本地化字符串。
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fake as 的本地化字符串。
        /// </summary>
        public static string FakeAs {
            get {
                return ResourceManager.GetString("FakeAs", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to load game_text: {0} 的本地化字符串。
        /// </summary>
        public static string FailedToLoadGameText {
            get {
                return ResourceManager.GetString("FailedToLoadGameText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 GoldSrc BSP 的本地化字符串。
        /// </summary>
        public static string GoldSrcBspFilter {
            get {
                return ResourceManager.GetString("GoldSrcBspFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUI language 的本地化字符串。
        /// </summary>
        public static string GuiLanguage {
            get {
                return ResourceManager.GetString("GuiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System default 的本地化字符串。
        /// </summary>
        public static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string LanguageSimplifiedChinese {
            get {
                return ResourceManager.GetString("LanguageSimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        public static string LanguageTraditionalChinese {
            get {
                return ResourceManager.GetString("LanguageTraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built-in 的本地化字符串。
        /// </summary>
        public static string LoadBuiltInPrompt {
            get {
                return ResourceManager.GetString("LoadBuiltInPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LLM 的本地化字符串。
        /// </summary>
        public static string Llm {
            get {
                return ResourceManager.GetString("Llm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel requested. 的本地化字符串。
        /// </summary>
        public static string LogCancelRequested {
            get {
                return ResourceManager.GetString("LogCancelRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save prompt file: {0} 的本地化字符串。
        /// </summary>
        public static string LogFailedToSavePromptFile {
            get {
                return ResourceManager.GetString("LogFailedToSavePromptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded built-in prompt. 的本地化字符串。
        /// </summary>
        public static string LogLoadedBuiltInPrompt {
            get {
                return ResourceManager.GetString("LogLoadedBuiltInPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded configuration: {0} 的本地化字符串。
        /// </summary>
        public static string LogLoadedConfiguration {
            get {
                return ResourceManager.GetString("LogLoadedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded prompt file: {0} 的本地化字符串。
        /// </summary>
        public static string LogLoadedPromptFile {
            get {
                return ResourceManager.GetString("LogLoadedPromptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No BSP files selected. 的本地化字符串。
        /// </summary>
        public static string LogNoBspFilesSelected {
            get {
                return ResourceManager.GetString("LogNoBspFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        public static string LogProgress {
            get {
                return ResourceManager.GetString("LogProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved configuration: {0} 的本地化字符串。
        /// </summary>
        public static string LogSavedConfiguration {
            get {
                return ResourceManager.GetString("LogSavedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved prompt file: {0} 的本地化字符串。
        /// </summary>
        public static string LogSavedPromptFile {
            get {
                return ResourceManager.GetString("LogSavedPromptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Markdown 的本地化字符串。
        /// </summary>
        public static string MarkdownFilter {
            get {
                return ResourceManager.GetString("MarkdownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No game_text messages were found. 的本地化字符串。
        /// </summary>
        public static string NoGameTextFound {
            get {
                return ResourceManager.GetString("NoGameTextFound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Prompt file 的本地化字符串。
        /// </summary>
        public static string PromptFile {
            get {
                return ResourceManager.GetString("PromptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional prompt .md path 的本地化字符串。
        /// </summary>
        public static string PromptFileWatermark {
            get {
                return ResourceManager.GetString("PromptFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt editor 的本地化字符串。
        /// </summary>
        public static string PromptEditor {
            get {
                return ResourceManager.GetString("PromptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit the prompt used when a prompt file is saved and selected 的本地化字符串。
        /// </summary>
        public static string PromptEditorWatermark {
            get {
                return ResourceManager.GetString("PromptEditorWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reasoning effort 的本地化字符串。
        /// </summary>
        public static string ReasoningEffort {
            get {
                return ResourceManager.GetString("ReasoningEffort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Raw game_text - {0} 的本地化字符串。
        /// </summary>
        public static string RawGameTextTitle {
            get {
                return ResourceManager.GetString("RawGameTextTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Reload file 的本地化字符串。
        /// </summary>
        public static string ReloadPromptFromFile {
            get {
                return ResourceManager.GetString("ReloadPromptFromFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string RemoveTask {
            get {
                return ResourceManager.GetString("RemoveTask", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save prompt 的本地化字符串。
        /// </summary>
        public static string SavePromptFile {
            get {
                return ResourceManager.GetString("SavePromptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save prompt file 的本地化字符串。
        /// </summary>
        public static string SavePromptFileTitle {
            get {
                return ResourceManager.GetString("SavePromptFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select BSP files 的本地化字符串。
        /// </summary>
        public static string SelectBspFilesTitle {
            get {
                return ResourceManager.GetString("SelectBspFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select prompt file 的本地化字符串。
        /// </summary>
        public static string SelectPromptFileTitle {
            get {
                return ResourceManager.GetString("SelectPromptFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building prompt 的本地化字符串。
        /// </summary>
        public static string StatusBuildingPrompt {
            get {
                return ResourceManager.GetString("StatusBuildingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled 的本地化字符串。
        /// </summary>
        public static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        public static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting game_text 的本地化字符串。
        /// </summary>
        public static string StatusExtractingGameText {
            get {
                return ResourceManager.GetString("StatusExtractingGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing response 的本地化字符串。
        /// </summary>
        public static string StatusParsingResponse {
            get {
                return ResourceManager.GetString("StatusParsingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queued 的本地化字符串。
        /// </summary>
        public static string StatusQueued {
            get {
                return ResourceManager.GetString("StatusQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requesting translation 的本地化字符串。
        /// </summary>
        public static string StatusRequestingTranslation {
            get {
                return ResourceManager.GetString("StatusRequestingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing dictionary 的本地化字符串。
        /// </summary>
        public static string StatusWritingDictionary {
            get {
                return ResourceManager.GetString("StatusWritingDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target language 的本地化字符串。
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature 的本地化字符串。
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string TranslateTab {
            get {
                return ResourceManager.GetString("TranslateTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 View raw game_text 的本地化字符串。
        /// </summary>
        public static string ViewRawGameText {
            get {
                return ResourceManager.GetString("ViewRawGameText", resourceCulture);
            }
        }
    }
}
